Repository canonical/mysql-k8s-operator, pull requests merged in 2025-02, with the labels that each got.

#583 [DPE-6653] Signal outdated charm libs with a label
  .github/workflows/check_libs.yaml
  .github/workflows/ci.yaml
Labels: not bug or enhancement, Libraries: Out of sync

#584 feat: dpe-6306 Static code analysis
  .github/actionlint.yaml
  .github/workflows/tiobe_scan.yaml
Labels: not bug or enhancement, Libraries: Out of sync

#592 fix: dpe-5164 ensure failed bootstrap cleanup
  src/charm.py
Labels: bug, Libraries: Out of sync

#594 [DPE-6651] Update rock tag for new builds with updated percona packages
  metadata.yaml
Labels: enhancement, Libraries: Out of sync

#598 Avoid using incompatible juju debug-log options in test helper
  tests/integration/helpers.py
Labels: not bug or enhancement, Libraries: Out of sync
