Repository canonical/mysql-k8s-operator, pull requests merged in 2025-09, with the labels that each got.

#635 [DPE-7322] Support predefined roles
  docs/reference/software-testing.md
  lib/charms/mysql/v0/mysql.py
  src/charm.py
  src/mysql_k8s_helpers.py
  src/relations/mysql.py
  src/relations/mysql_provider.py
  src/relations/mysql_root.py
  tests/integration/high_availability/high_availability_helpers.py
  tests/integration/relations/test_mysql_root.py
  tests/integration/roles/__init__.py
  tests/integration/roles/test_database_dba_role.py
  tests/integration/roles/test_instance_dba_role.py
  tests/integration/roles/test_instance_roles.py
  tests/spread/test_database_dba_role.py/task.yaml
  tests/spread/test_instance_dba_role.py/task.yaml
  tests/spread/test_instance_roles.py/task.yaml
  tests/unit/test_charm.py
  tests/unit/test_database.py
  tests/unit/test_mysql_k8s_helpers.py
Labels: enhancement, Libraries: Out of sync

#657 Fix alert rules screenshot
  docs/how-to/monitoring-cos/alert-rules-grafana.png
  docs/how-to/monitoring-cos/enable-alert-rules.md
Labels: bug, documentation

#659 [MISC] Fix OSM integration test
  tests/integration/test_osm_integration_bundle.py
  tests/spread/test_osm_integration_bundle.py/task.yaml
Labels: bug, Libraries: Out of sync

#658 [DPE-7322] Tweak database DBA role naming
  docs/explanation/roles.md
  lib/charms/mysql/v0/mysql.py
  tests/integration/roles/test_database_dba_role.py
Labels: enhancement, Libraries: Out of sync
