Repository canonical/mysql-k8s-operator, pull requests merged in 2025-03, with the labels that each got.

#602 Create coverage report for tiobe
  tox.ini
Labels: Libraries: Out of sync

#593 [DPE-6488] Port over mysql charmlib changes from vm operator related to unit initialized
  lib/charms/mysql/v0/async_replication.py
  lib/charms/mysql/v0/mysql.py
  lib/charms/mysql/v0/tls.py
  src/charm.py
  src/log_rotate_manager.py
  src/mysql_k8s_helpers.py
  src/relations/mysql.py
  src/relations/mysql_provider.py
  src/relations/mysql_root.py
  src/rotate_mysql_logs.py
  src/upgrade.py
  tests/integration/high_availability/test_crash_during_setup.py
  tests/unit/test_charm.py
  tests/unit/test_upgrade.py
Labels: not bug or enhancement, Libraries: Out of sync

#600 DPE-6487 Pitr
  actions.yaml
  lib/charms/mysql/v0/architecture.py
  lib/charms/mysql/v0/backups.py
  lib/charms/mysql/v0/mysql.py
  lib/charms/mysql/v0/s3_helpers.py
  src/charm.py
  src/constants.py
  src/mysql_k8s_helpers.py
  src/upgrade.py
  tests/integration/backups.py
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_backup_aws.py
  tests/integration/test_backup_ceph.py
  tests/integration/test_backup_gcp.py
  tests/integration/test_backup_pitr_aws.py
  tests/integration/test_backup_pitr_gcp.py
  tests/spread/test_backup_pitr_aws.py/task.yaml
  tests/spread/test_backup_pitr_gcp.py/task.yaml
  tests/unit/test_charm.py
Labels: enhancement, Libraries: Out of sync

#605 doc: DPE-6312 security policy
  SECURITY.md
Labels: documentation, not bug or enhancement
